export const FETCH_PRODUCTS = 'FETCH_PRODUCTS';
export const SORT = 'SORT';
export const FILTER_PRICE = 'FILTER_PRICE';
export const FILTER_PRICE_REMOVER = 'FILTER_PRICE_REMOVER';
export const FILTER_CATEGORY = 'FILTER_CATEGORY';
export const SEARCH = 'SEARCH'
